### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by adriangalilea** [ymgyt/syndicationd#119]
On [this discussion ](https://github.com/ymgyt/syndicationd/discussions/117)I mentioned:

> Also consider having a config file, also respecting $XDG_CONFIG_.../syndicationd/ as a default for the config path. In Go there's [this library](https://github.com/adrg/xdg) that [I use](https://github.com/adriangalilea/xdg-dirs) which you may be able to leverage or find a similar one for rust. Will be helpful for consolidating some settings.

Settings which I think would make more sense to use a config file with:

- `THEME`
- `LOG_PATH`
- `CACHE_DIR`
- `ENABLE_GH`
- `SYND_GH_PAT` (this should be safe as long as permissions are only for reading notifs)

I would still respect the env variables, just have a config file too.

P.S.: this is not anything urgent as there are means to set anything you want to set, so focus elsewhere, just wanted to define the task for whenever you find it reasonable to implement, if at all.

**Comment by ymgyt** [comment]
Thank you for creating the issue. As the number of configuration options has increased,  I intend to support command-line arguments, environment variables, configuration files, and default values as methods for configuration (in order of priority).

**Comment by ymgyt** [comment]
I have merged the [support for the initial configuration file](https://github.com/ymgyt/syndicationd/commit/86d7b246276193d8790cb3bc0a092789919c7e19) into the main branch. We plan to release it once the text browser integration is completed.

**Comment by ymgyt** [comment]
We have added support for a config file in the [v0.3.1 release](https://github.com/ymgyt/syndicationd/releases/tag/synd-term-v0.3.1).
 You can specify the path using either the `--config` flag or the `SYND_CONFIG_FILE` environment variable. 
For more details, please refer to the [documentation](https://github.com/ymgyt/syndicationd?tab=readme-ov-file#configuration).
 Thank you again for your suggestion!
